# Generated by Django 5.2.2 on 2025-06-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(help_text='Nome do ícone SVG ou URL da imagem', max_length=100)),
                ('cor_fundo', models.CharField(default='#f3eaff', help_text='Cor de fundo do card (ex: #f3eaff)', max_length=30)),
                ('slug', models.SlugField(help_text='URL do quiz, ex: matematica, ciencias', unique=True)),
            ],
        ),
    ]
